# Placeholders:
# {server} - Current server name
# {player} - Player name
# {message} - Message sent
# {displayName} - Channel display name (defined by the displayName config option)

botToken: "token"

# Premium Vanish Database Hook
sql:
  database: "database"
  host: "127.0.0.0"
  username: "root"
  password: "password"
channels:
  staff:
    displayName: "&4&lStaff"
    permission: "staffchat.staff"
    chatColor: "&c"
    chatPrefix: "#"
    command: "sc"
    commandAliases: ["staffchat", "staffc"]
    moveMessages: true
    discordChannel: "328923486723845"
    format: "&c[{displayName}&c] &f| &c{server} &f| &c{player} &7» &c{message}"