botToken: token
channels:
  staff:
    displayName: "&4&lStaff"
    permission: "staffchat.staff"
    chatColor: "&c"
    chatPrefix: "#"
    command: "sc"
    commandAliases: ["staffchat", "staffc"]
    moveMessages: true
    discordChannel: 328923486723845
    format: "&c[&4&lStaff&c] &f| &c{server} &f| &c{player} &7» &c{message}"