botToken: token
channels:
  staff:
    displayName: "&4&lStaff"
    permission: "staffchat.staff"
    chatColor: "&c"
    chatPrefix: "#"
    command: "sc"
    commandAliases: ["staffchat", "staffc"]
    moveMessages: true
    discordChannel: 328923486723845